name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build with alternative Docker image
      run: |
        docker run --rm \
          -v $PWD:/src \
          -w /src \
          kivy/buildozer:latest \
          buildozer android debug
