name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # Меняем на LATEST вместо 20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-11-jdk
        
    - name: Install Buildozer
      run: |
        pip install buildozer
        
    - name: Build APK
      run: |
        buildozer -v android debug
