name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install everything
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk
        pip3 install buildozer cython==0.29.19
        
    - name: Build APK
      run: |
        buildozer -v android debug
