name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build APK with Buildozer
      uses: ugi/bitrise-step-buildozer-android@v1
      with:
        buildozer-version: '1.5.0'
