name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build with Buildozer Docker
      run: |
        docker run --rm \
          -v $PWD:/home/buildozer/android \
          -w /home/buildozer/android \
          crazymax/buildozer:latest \
          buildozer android debug
